
# spring.datasource.url=jdbc:mysql://localhost:3306/petconsultant?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=Malik@123
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # ===========================
# # JPA / Hibernate

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# spring.jpa.properties.hibernate.format_sql=true

# app.jwt.secret=UGV0Q29uc3VsdGFudFNlY3JldEtleTIwMjRQZXRDb25zdWx0YW50U2VjcmV0S2V5
# app.jwt.expiration=86400000

# # ===========================
# # Application
# # ===========================
# spring.application.name=PetConsultantAPI

# server.port=8082
# server.servlet.context-path=/test

spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=IUyNwAYxzzMCTQSJekJdtbrrolLTfdEK

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}
server.servlet.context-path=/test